app = "the-one"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_APP = "run.py"
  FLASK_ENV = "production"
  SECRET_KEY = "c0abe021f9cff196d74b17f27a3ecf64ffe76abe3059143813221d78d97fd2fb"
  FIRECRAWL_API_KEY = "fc-c9b26ff85a964f1aaf8ae70aab2ba002"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  source = "the_one_data"
  destination = "/data"

[deploy]
  release_command = "python init_db.py"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]